In [3]:
import polars as pl
import time

## Big Data e Processamento Otimizado com Python II

### Manipulação do Parquet e StringCache

In [6]:
inicial = (
    pl.scan_parquet("C:/Users/thalyta.martins/Documents/Visual Studio 2017/bigdatasenac/analistadedadossenac-1/202501_NovoBolsaFamilia_PANDAS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
)

display(inicial.collect())

shape: (19_480_034, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202502     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202502     ┆ RO  ┆ 5          ┆ … ┆ ***.582.08 ┆ 1622464294 ┆ GLEISIMAR ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ LIMA      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202503     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202505     ┆ SP  ┆ 2965       ┆ … ┆ ***.740.01 ┆ 2061952103 ┆ LIGIA     ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 4-**       ┆ 6          ┆ SAMARA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA DOS  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆ ***.124.31 ┆ 1639916382 ┆ CLEICIANE ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ SOUZA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RIBEIRO   ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202601     ┆ 202601     ┆ TO  ┆ 9643       ┆ … ┆ ***.273.19 ┆ 2064488199 ┆ ZENILDE   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 7          ┆ ALVES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202601     ┆ 202601     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 1273938997 ┆ ZENILDE   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 5          ┆ GONCALVES ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
│ 202601     ┆ 202601     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 1905866197 ┆ ZENOLIA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ RAMOS DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARVALH…  ┆           │
│ 202601     ┆ 202601     ┆ TO  ┆ 9643       ┆ … ┆ ***.822.65 ┆ 2091926382 ┆ ZILMA     ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 2          ┆ ALVES DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BARROS    ┆           │
│ 202601     ┆ 202601     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 2050119994 ┆ ZULEIDE   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ DA SILVA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ E SILVA   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

### Filtros
Para selecionar linhas baseadas em condições lógicas (semelhante ao WHERE do SQL).

In [5]:
# Filtro Simples: Apenas beneficiários do Rio de Janeiro
q_rj = inicial.filter(pl.col("UF") == "RJ")

# Filtro Composto (E / OU): RJ e valor maior que 800
q_rj_alto = inicial.filter(
    (pl.col("UF") == "RJ") & (pl.col("VALOR PARCELA") > 800)
)

# Filtro com Lista (IS IN): Apenas estados do Sudeste
q_sudeste = inicial.filter(
    pl.col("UF").is_in(["SP", "RJ", "MG", "ES"])
)

display(q_rj.collect())
display(q_rj_alto.collect())
display(q_sudeste.collect())

shape: (1_482_055, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202506     ┆ RJ  ┆ 5801       ┆ … ┆            ┆ 1685810469 ┆ DAYANNE   ┆ 700.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 1          ┆ DA CUNHA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ PIMENTEL  ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5801       ┆ … ┆            ┆ 1176008871 ┆ GILMARA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 9          ┆ SANTANA   ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5801       ┆ … ┆ ***.620.57 ┆ 2369246349 ┆ LUCIA     ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 5          ┆ ROSA DA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CONCEICAO ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5801       ┆ … ┆            ┆ 1333688360 ┆ LUIZ      ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 0          ┆ ANTONIO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ PIRES     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RAMOS     ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5801       ┆ … ┆ ***.766.14 ┆ 2041506980 ┆ NAIARA    ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 1          ┆ MUNIZ DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.015.58 ┆ 1663703730 ┆ ZILTA     ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 4          ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ PAULISTA  ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆            ┆ 1314378560 ┆ ZITIELEN  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CAETANO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BIT…      ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.546.28 ┆ 2372406310 ┆ ZIULANDA  ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 1          ┆ NICOLAU   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.649.99 ┆ 2003805509 ┆ ZULEICA   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 5          ┆ FLORENTIN ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ O DA      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.616.18 ┆ 1276120760 ┆ ZULEIGA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 4          ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (175_451, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202506     ┆ RJ  ┆ 5803       ┆ … ┆            ┆ 1905976425 ┆ TATIANA   ┆ 810.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ SANTOS DA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 770        ┆ … ┆ ***.132.43 ┆ 1616748941 ┆ ADRIELLY  ┆ 960.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ LEAL      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MENDES    ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5805       ┆ … ┆ ***.550.44 ┆ 2099324359 ┆ PATRICIA  ┆ 860.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ LESSA DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5807       ┆ … ┆ ***.081.53 ┆ 1619804997 ┆ JESSICA   ┆ 860.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 4          ┆ OLIVEIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202506     ┆ RJ  ┆ 5807       ┆ … ┆ ***.242.48 ┆ 1664247356 ┆ SINTIA    ┆ 1010.0    │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ DAMAZIO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DOS REIS  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.439.96 ┆ 2019052041 ┆ YASMIN    ┆ 1060.0    │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 2          ┆ NICOLE    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COSTA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RODRIGUES ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆            ┆ 1632506078 ┆ YRIS      ┆ 1000.0    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 5          ┆ GABRIELLY ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.535.48 ┆ 2007543406 ┆ YSIS      ┆ 860.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 1          ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆            ┆ 1370780403 ┆ YURAIMA   ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ JOSEFINA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARREAZA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ROCA      ┆           │
│ 202601     ┆ 202601     ┆ RJ  ┆ 5925       ┆ … ┆ ***.936.33 ┆ 2077635202 ┆ ZEZABEL   ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 9          ┆ ESTEVAO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COSTA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ALMEI…    ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (5_628_687, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202502     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202503     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202505     ┆ SP  ┆ 2965       ┆ … ┆ ***.740.01 ┆ 2061952103 ┆ LIGIA     ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 4-**       ┆ 6          ┆ SAMARA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA DOS  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202601     ┆ 202506     ┆ ES  ┆ 5601       ┆ … ┆ ***.063.41 ┆ 1615331681 ┆ ALFALINA  ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ NEVES DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202506     ┆ ES  ┆ 5601       ┆ … ┆ ***.552.16 ┆ 1615375644 ┆ ANA PAULA ┆ 722.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 2          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202601     ┆ 202601     ┆ SP  ┆ 2973       ┆ … ┆ ***.666.88 ┆ 1655569782 ┆ VALERIA   ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 3          ┆ ALVES     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GOULART   ┆           │
│ 202601     ┆ 202601     ┆ SP  ┆ 2973       ┆ … ┆            ┆ 2049170098 ┆ VANDERSON ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ DIOGO DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202601     ┆ SP  ┆ 2973       ┆ … ┆ ***.960.04 ┆ 1658316052 ┆ WELINGTON ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 9          ┆ LUCAS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BATISTA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COELHO    ┆           │
│ 202601     ┆ 202601     ┆ SP  ┆ 2973       ┆ … ┆ ***.074.43 ┆ 2043678790 ┆ WESLEY    ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ JUNIOR DA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SIMPLIC…  ┆           │
│ 202601     ┆ 202601     ┆ SP  ┆ 2973       ┆ … ┆            ┆ 2138499203 ┆ YASMIM    ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ PISTOLATO ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MECIANO   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

### Seleção e Exclusão
Para escolher ou remover colunas específicas.

In [7]:
# Selecionar apenas colunas de interesse
q_simples = inicial.select(["UF", "NOME_MUNICIPIO", "VALOR PARCELA"])

# .drop() remove as colunas listadas
q_sem_codigos = inicial.drop(["CODIGO_MUNICIPIO_SIAFI", "NIS FAVORECIDO"])

# Seleciona tudo (implícito) excluindo as colunas listadas
q_sem_codigos = inicial.select(pl.exclude(["CODIGO_MUNICIPIO_SIAFI", "NIS FAVORECIDO"]))

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (19_480_034, 3)
┌─────┬────────────────┬───────────────┐
│ UF  ┆ NOME_MUNICIPIO ┆ VALOR PARCELA │
│ --- ┆ ---            ┆ ---           │
│ str ┆ str            ┆ f64           │
╞═════╪════════════════╪═══════════════╡
│ MG  ┆ PONTE NOVA     ┆ 850.0         │
│ RO  ┆ JI-PARANA      ┆ 750.0         │
│ MG  ┆ PONTE NOVA     ┆ 850.0         │
│ SP  ┆ BERTIOGA       ┆ 800.0         │
│ AC  ┆ ACRELANDIA     ┆ 850.0         │
│ …   ┆ …              ┆ …             │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 650.0         │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 650.0         │
└─────┴────────────────┴───────────────┘

shape: (19_480_034, 7)
┌────────────────┬────────────────┬─────┬────────────────┬───────────────┬───────────────┬─────────┐
│ MES_COMPETENCI ┆ MES_REFERENCIA ┆ UF  ┆ NOME_MUNICIPIO ┆ CPF           ┆ NOME          ┆ VALOR   │
│ A              ┆ ---            ┆ --- ┆ ---            ┆ FAVORECIDO    ┆ FAVORECIDO    ┆ PARCELA │
│ ---            ┆ i64            ┆ str ┆ str            ┆ ---           ┆ ---           ┆ ---     │
│ i64            ┆                ┆     ┆                ┆ str           ┆ str           ┆ f64     │
╞════════════════╪════════════════╪═════╪════════════════╪═══════════════╪═══════════════╪═════════╡
│ 202601         ┆ 202502         ┆ MG  ┆ PONTE NOVA     ┆               ┆ MILENE        ┆ 850.0   │
│                ┆                ┆     ┆                ┆               ┆ APARECIDA     ┆         │
│                ┆                ┆     ┆                ┆               ┆ SILVA DE      ┆         │
│                ┆                ┆     ┆                ┆               ┆ ARAU…         ┆         │
│ 202601         ┆ 202502         ┆ RO  ┆ JI-PARANA      ┆ ***.582.082-* ┆ GLEISIMAR     ┆ 750.0   │
│                ┆                ┆     ┆                ┆ *             ┆ LIMA SILVA    ┆         │
│ 202601         ┆ 202503         ┆ MG  ┆ PONTE NOVA     ┆               ┆ MILENE        ┆ 850.0   │
│                ┆                ┆     ┆                ┆               ┆ APARECIDA     ┆         │
│                ┆                ┆     ┆                ┆               ┆ SILVA DE      ┆         │
│                ┆                ┆     ┆                ┆               ┆ ARAU…         ┆         │
│ 202601         ┆ 202505         ┆ SP  ┆ BERTIOGA       ┆ ***.740.014-* ┆ LIGIA SAMARA  ┆ 800.0   │
│                ┆                ┆     ┆                ┆ *             ┆ LIMA DOS      ┆         │
│                ┆                ┆     ┆                ┆               ┆ SANTOS        ┆         │
│ 202601         ┆ 202506         ┆ AC  ┆ ACRELANDIA     ┆ ***.124.312-* ┆ CLEICIANE     ┆ 850.0   │
│                ┆                ┆     ┆                ┆ *             ┆ SOUZA RIBEIRO ┆         │
│ …              ┆ …              ┆ …   ┆ …              ┆ …             ┆ …             ┆ …       │
│ 202601         ┆ 202601         ┆ TO  ┆ XAMBIOA        ┆ ***.273.191-* ┆ ZENILDE ALVES ┆ 600.0   │
│                ┆                ┆     ┆                ┆ *             ┆ DOS SANTOS    ┆         │
│ 202601         ┆ 202601         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZENILDE       ┆ 650.0   │
│                ┆                ┆     ┆                ┆               ┆ GONCALVES DE  ┆         │
│                ┆                ┆     ┆                ┆               ┆ OLIVEIRA      ┆         │
│ 202601         ┆ 202601         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZENOLIA RAMOS ┆ 600.0   │
│                ┆                ┆     ┆                ┆               ┆ DA SILVA      ┆         │
│                ┆                ┆     ┆                ┆               ┆ CARVALH…      ┆         │
│ 202601         ┆ 202601         ┆ TO  ┆ XAMBIOA        ┆ ***.822.651-* ┆ ZILMA ALVES   ┆ 600.0   │
│                ┆                ┆     ┆                ┆ *             ┆ DE BARROS     ┆         │
│ 202601         ┆ 202601         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZULEIDE DA    ┆ 650.0   │
│                ┆                ┆     ┆                ┆               ┆ SILVA E SILVA ┆         │
└────────────────┴────────────────┴─────┴────────────────┴───────────────┴───────────────┴─────────┘

### Condicionais
Criar novas colunas com base em lógica (semelhante ao IF do Excel ou CASE WHEN do SQL).

In [8]:
# Categorizar o pagamento
q_categoria = inicial.with_columns(
    pl.when(pl.col("VALOR PARCELA") >= 900)
    .then(pl.lit("Alto Valor"))
    .when(pl.col("VALOR PARCELA") > 600)
    .then(pl.lit("Médio Valor"))
    .otherwise(pl.lit("Básico"))
    .alias("CATEGORIA_PAGAMENTO")
)

display(q_categoria.select(["VALOR PARCELA", "CATEGORIA_PAGAMENTO"]).collect())

shape: (19_480_034, 2)
┌───────────────┬─────────────────────┐
│ VALOR PARCELA ┆ CATEGORIA_PAGAMENTO │
│ ---           ┆ ---                 │
│ f64           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ 850.0         ┆ Médio Valor         │
│ 750.0         ┆ Médio Valor         │
│ 850.0         ┆ Médio Valor         │
│ 800.0         ┆ Médio Valor         │
│ 850.0         ┆ Médio Valor         │
│ …             ┆ …                   │
│ 600.0         ┆ Básico              │
│ 650.0         ┆ Médio Valor         │
│ 600.0         ┆ Básico              │
│ 600.0         ┆ Básico              │
│ 650.0         ┆ Médio Valor         │
└───────────────┴─────────────────────┘

In [6]:
# Partindo do LazyFrame 'q_categoria' já criado
q_analise_categoria = (
    q_categoria
    .group_by("CATEGORIA_PAGAMENTO")
    .agg([
        pl.len().alias("total_beneficiarios"),
        pl.col("VALOR PARCELA").mean().alias("media_pagamento"),
        pl.col("VALOR PARCELA").min().alias("menor_pagamento"),
        pl.col("VALOR PARCELA").max().alias("maior_pagamento"),
        pl.col("VALOR PARCELA").sum().alias("total_investido")
    ])
    .sort("media_pagamento", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ CATEGORIA_PAGA ┆ total_benefici ┆ media_pagament ┆ menor_pagamen ┆ maior_pagamen ┆ total_investi │
│ MENTO          ┆ arios          ┆ o              ┆ to            ┆ to            ┆ do            │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ u32            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Alto Valor     ┆ 2103126        ┆ 1038.537427    ┆ 900.0         ┆ 3938.0        ┆ 2.1842e9      │
│ Médio Valor    ┆ 9657874        ┆ 724.877575     ┆ 601.0         ┆ 898.0         ┆ 7.0008e9      │
│ Básico         ┆ 8739422        ┆ 520.723108     ┆ 25.0          ┆ 600.0         ┆ 4.5508e9      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

### Fatiamento
Para pegar "pedaços" dos dados. No modo Lazy, o slice é muito eficiente pois o Polars lê apenas o necessário do disco.

In [9]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150 (offset 100, length 50)
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202502     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202502     ┆ RO  ┆ 5          ┆ … ┆ ***.582.08 ┆ 1622464294 ┆ GLEISIMAR ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ LIMA      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202503     ┆ MG  ┆ 5041       ┆ … ┆            ┆ 1652366711 ┆ MILENE    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARAU…     ┆           │
│ 202601     ┆ 202505     ┆ SP  ┆ 2965       ┆ … ┆ ***.740.01 ┆ 2061952103 ┆ LIGIA     ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 4-**       ┆ 6          ┆ SAMARA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA DOS  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆ ***.124.31 ┆ 1639916382 ┆ CLEICIANE ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ SOUZA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RIBEIRO   ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆            ┆ 2120826344 ┆ EGILA     ┆ 300.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 9          ┆ WENZEL DA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆ ***.670.22 ┆ 1647084848 ┆ KEILA     ┆ 375.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 7          ┆ NEVES DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOUZA     ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆ ***.264.18 ┆ 1644094602 ┆ LUCIANA   ┆ 400.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 2          ┆ LUCAS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MESQUITA  ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆            ┆ 1426245062 ┆ MARIA     ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ RAIMUNDA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ PEREIRA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MARCOLI…  ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 643        ┆ … ┆            ┆ 2049904108 ┆ MIQUELE   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ VALENTIM  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE SOUZA  ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (50, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202601     ┆ 202506     ┆ AC  ┆ 151        ┆ … ┆ ***.665.02 ┆ 2045301871 ┆ RAILA     ┆ 400.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 2          ┆ CRISTINA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE MEL…   ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 151        ┆ … ┆            ┆ 2138567636 ┆ VITORIA   ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ VASQUES   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA      ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 649        ┆ … ┆ ***.124.49 ┆ 1665314284 ┆ NILZELENE ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 2          ┆ DE SOUZA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ NOBRE     ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 649        ┆ … ┆            ┆ 2137192079 ┆ VANIA DE  ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 8          ┆ SOUZA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ FERREIRA  ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 657        ┆ … ┆ ***.969.02 ┆ 1622633004 ┆ FRANCISCA ┆ 300.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOUZA     ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202601     ┆ 202506     ┆ AC  ┆ 139        ┆ … ┆            ┆ 1619866026 ┆ FERNANDA  ┆ 380.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 6          ┆ OLIVEIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GOMES     ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 139        ┆ … ┆ ***.725.24 ┆ 2005684224 ┆ FRANCINET ┆ 300.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 9          ┆ E         ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RODRIGUES ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DO        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ NASCIM…   ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 139        ┆ … ┆ ***.527.81 ┆ 2076975289 ┆ FRANCISCA ┆ 400.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ BRENA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ FERNANDES ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GADE…     ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 139        ┆ … ┆            ┆ 2010653661 ┆ FRANCISCA ┆ 405.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 8          ┆ DA SILVA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202601     ┆ 202506     ┆ AC  ┆ 139        ┆ … ┆ ***.119.34 ┆ 1263777500 ┆ FRANCISCA ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 0          ┆ DO NASCIM ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ENTO      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RODRIG…   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [8]:
# Recorte de linhas specíficas (ex: linha 0, 10 e 50)
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")  # Cria uma coluna temporária com o número da linha
    .filter(pl.col("id_linha").is_in([0, 10, 50])) # Filtra pelos números desejados
    .select(["UF", "NOME_MUNICIPIO"]) # Seleciona as colunas
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌─────┬────────────────┐
│ UF  ┆ NOME_MUNICIPIO │
│ --- ┆ ---            │
│ str ┆ str            │
╞═════╪════════════════╡
│ SP  ┆ SANTOS         │
│ SP  ┆ SANTOS         │
│ PR  ┆ GUARAPUAVA     │
└─────┴────────────────┘

### Agrupamento Avançado (group_by + agg)

In [10]:
q_stats_mun = (
    inicial.group_by("NOME_MUNICIPIO")
    .agg([
        pl.len().alias("total_familias"),  # Contagem rápida
        pl.col("VALOR PARCELA").sum().alias("total_repassado"),
        pl.col("VALOR PARCELA").max().alias("maior_pagamento"),
        pl.col("UF").first().alias("uf_origem") # Mantém a UF do municipio
    ])
    .sort("total_repassado", descending=True)
)

display(q_stats_mun.collect())

shape: (5_292, 5)
┌───────────────────┬────────────────┬─────────────────┬─────────────────┬───────────┐
│ NOME_MUNICIPIO    ┆ total_familias ┆ total_repassado ┆ maior_pagamento ┆ uf_origem │
│ ---               ┆ ---            ┆ ---             ┆ ---             ┆ ---       │
│ str               ┆ u32            ┆ f64             ┆ f64             ┆ str       │
╞═══════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════╡
│ SAO PAULO         ┆ 678398         ┆ 4.38222589e8    ┆ 3322.0          ┆ SP        │
│ RIO DE JANEIRO    ┆ 457465         ┆ 2.96438103e8    ┆ 2788.0          ┆ RJ        │
│ FORTALEZA         ┆ 301528         ┆ 1.93254267e8    ┆ 2362.0          ┆ CE        │
│ SALVADOR          ┆ 283852         ┆ 1.81817653e8    ┆ 2512.0          ┆ BA        │
│ MANAUS            ┆ 246600         ┆ 1.67236291e8    ┆ 2838.0          ┆ AM        │
│ …                 ┆ …              ┆ …               ┆ …               ┆ …         │
│ CORONEL PILAR     ┆ 7              ┆ 3802.0          ┆ 722.0           ┆ RS        │
│ BRACO DO TROMBUDO ┆ 8              ┆ 3756.0          ┆ 651.0           ┆ SC        │
│ CUNHATAI          ┆ 5              ┆ 3235.0          ┆ 960.0           ┆ SC        │
│ MONTAURI          ┆ 6              ┆ 3175.0          ┆ 900.0           ┆ RS        │
│ SANTA TEREZA      ┆ 5              ┆ 2780.0          ┆ 650.0           ┆ RS        │
└───────────────────┴────────────────┴─────────────────┴─────────────────┴───────────┘

### StringCache e Otimização de CPU

Como estamos na fase de pré-processamento de Big Data, precisamos conectar o conceito de hardware com o código.

#### O Problema da String: 

Textos são "pesadas" para a CPU processar. Comparar a palavra "RIO DE JANEIRO" com "RIO DE JANEIRO" exige verificar letra por letra. Isso ocupa muito espaço na memória Cache (L1/L2/L3) do processador, que é ultrarrápida mas muito pequena.

Uma solução? Em vez de guardar a palavra "SP" milhões de vezes, o computador cria um dicionário: 0 = SP, 1 = RJ. Ele processa números (inteiros), o que é mais rápido para a CPU.

O **StringCache** do Polars: Garante que esse dicionário seja GLOBAL.

- *Sem StringCache*: Se você tiver dois DataFrames, "SP" pode ser o código 0 no primeiro e o código 5 no segundo. Isso impede junções (joins) corretas sem recriar os dados.

- *Com StringCache*: "SP" será o código 0 em qualquer operação enquanto o cache estiver ativo.

#### Vantagens Técnicas:

Uso de Memória RAM: Em colunas com *baixa cardinalidade* (muita repetição, como UF ou NOME_MUNICIPIO), o uso de memória cai drasticamente.

Velocidade em Joins e Agrupamentos: Agrupar por inteiros é muito mais rápido do que por strings para a lógica computacional.

In [12]:
print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet("C:/Users/thalyta.martins/Documents/Visual Studio 2017/bigdatasenac/analistadedadossenac-1/202501_NovoBolsaFamilia_PANDAS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
    .group_by(["UF", "NOME_MUNICIPIO"]) 
    .agg([
        pl.col("VALOR PARCELA").mean().alias("media"),
        pl.col("VALOR PARCELA").std().alias("desvio")
    ])
    .sort("media", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()
tempo_sem = end_1 - start_1
print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_1['UF'].estimated_size()} bytes\n")

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 5.1774 segundos
Uso de memória estimado (coluna UF): 11142 bytes

In [13]:
print("=== TESTE 2: Processamento COM StringCache ===")
# O StringCache funciona como um contexto (with)
with pl.StringCache():
    start_2 = time.time()
    
    q_com_cache = (
    pl.scan_parquet("C:/Users/thalyta.martins/Documents/Visual Studio 2017/bigdatasenac/analistadedadossenac-1/202602_NovoBolsaFamilia_PANDAS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
    .group_by(["UF", "NOME_MUNICIPIO"]) 
    .agg([
        pl.col("VALOR PARCELA").mean().alias("media"),
        pl.col("VALOR PARCELA").std().alias("desvio")
    ])
    .sort("media", descending=True)
)
    
    df_2 = q_com_cache.collect() # Ação!
    end_2 = time.time()

tempo_com = end_2 - start_2
print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_2['UF'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===

C:\Users\thalyta.martins\AppData\Local\Temp\ipykernel_18196\2706842360.py:3: DeprecationWarning: the string cache has been replaced by pl.Categories
  with pl.StringCache():

Tempo COM Cache: 1.2857 segundos
Uso de memória estimado (coluna UF): 11142 bytes